### ISSUE TITLE
Please provide the poster pdf "Abecedary Tracking and Mapping: a Toolkit for Tracking Competitions"

### ISSUE THREAD

**Issue by pbk0** [CVfAR/ATAM#1]
Thanks for the open source code. It helps to experiment with VR applications. I am not able to find your poster online. Is it possible for you to provide us with your poster presentation. 
Thanks praveen

**Comment by CVfAR** [comment]
Thank you for having your interest on our work. Can you download the poster from the following site?
http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7328103

**Comment by pbk0** [comment]
Thanks. You can also add the link to README file.   :+1:
